version: '3.8'

volumes:
  datafiles:

services:
  mysql:
    image: mysql:8.0.0
    container_name: tea_store_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_TCP_PORT=3306
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306

  website:
    container_name: tea_store_php
    image: tea_store_php_image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=secret
      #- MYSQL_DBNAME=
    volumes:
      - ./views:/var/www/html
    ports:
      - 8080:80
      - 8083:443
    depends_on:
      - mysql

  node-app:
    container_name: tea_store_node
    image: tea_store_node_image
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - ./app.js:/usr/src/app/app.js
    ports:
      - 8082:8001